version: '2'
services:
  proyectov1-app:
    image: proyectov1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://proyectov1-postgresql:5432/ProyectoV1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  proyectov1-postgresql:
    extends:
      file: postgresql.yml
      service: proyectov1-postgresql
